### ISSUE TITLE
Fundamental issues with 5d diplomacy(Discussion)

### ISSUE THREAD

**Issue by Pagwin-Fedora** [Oliveriver/5d-diplomacy-with-multiverse-time-travel#1]
I created this issue to create a more formal location for people(probably just me) to discuss the issues that were brought up in the [youtube video](https://www.youtube.com/watch?v=2__NGeY5JUw) as youtube comments are not directly associated with this repo  and are sub optimal for other reasons. Perhaps this should be broken up into multiple issues, we'll see. To describe the issues indicated in the video

## Adjustment
when do the active forces on the board get brought up or down to be equivalent to the number of supply centers on the board and what supply centers get counted

## Victory Condition(s)
how does a player or player(s) win? Winning on one board is a possibility but at small scales it makes things a bit too swingy or easy allowing for victory without a true sense of winning, as said in the video with the current prototype you can just control 2 supply centers on a random board which isn't very hard or difficult further once boards get bigger it can make every board that's close to resolution into a massive mess which is kinda the point of the timelines but having it take place on every board that's about to end seems like it'd be non-ideal. Another issue with copying 5d chess on this is what happens if different players win on different boards simultaneously, it's possible because everyone takes their turn at the same time.  The only obvious alternative to winning any one board of winning every board seems just infeasible on the face of it, there's a reason 5d chess doesn't have you win every board. 

## Misc issues that are equally problematic
* Where do the timelines go visually? with 2 players you can have all the timelines of 1 player go on top and the others go on the bottom with more it becomes unclear
* What are the rules for time line creation? Is there a limit, if not what stops one player from continuously making new timelines to stall the game out
* Game viability? Can this all come together to make a fun understandable(without quadruple digit iq) game

**Comment by Pagwin-Fedora** [comment]
my own personal thoughts on solutions for these issues are as follows

To start with adjustment I'd say that adjustment goes by the time axis. The number of units added or taken away should be decided by the supply centers owned on the board being evaluated for adjustment. This seems like a simple solution to this problem that also gives a reason to use the multiverse time travel other than stalling as you move units out of a timeline before an adjustment to avoid losing them or to gain more units than you wou ld otherwise though this may cause issues that are not obvious in my somewhat tired state at time or writing.

For the victory condition I personally think a good victory condition is to achieve victory on the original timeline. For timelines created via time travel victory would end the timeline in a sort of happily ever after state although for the purposes of gameplay what victory would mean on a non-primary board is that the board would remove all units and supply centers of the non-victor and allow the victor to move the units they have and get from supply centers out onto other boards which would provide incentive to win on boards other than the original but would also allow for sneaky victories to be achieved due to over commitment on boards outside of the original.

For timeline visuals I think the best solution is to just have timelines appear in the order they were created in top to bottom for games with more than 2 players, other solutions would probably be more complicated and hard to understand.

no idea what the timeline creation rules should be so I'm just gonna list out a couple of options I can think of, a fixed number of timelines could be set as the max of maybe 1 or 2 timeline creations per player, another solution could be 1 timeline creation per player and if you win a board you get another timeline creation if you want and least preferably 5d chess could be copied where each player cannot create more than 1 active timeline more than the amount of all the other players though this would probably cause issues in 7 player settings where being the 7th person to create a timeline is discouraged because all of a sudden everyone else can create a timeline again and make things more complicated and benefitial for them.

For movement to other timelines I'd say that a unit can move or support a unit going to the space it's on in the past or another timeline but cannot change the space it's on and it's higher dimension position at the same time just to keep the number of things to keep track of when defending a space to a reasonable number and avoid four digit iq being needed

for making the game understandable without four digit iq I think one way this could be achieved is to have each country played by a team of players with each player getting control of 1 timeline as timelines are created or to use the fixed number of timelines solution for the previous problem so the player only needs to deal with a managable and shrinking population of boards

**Comment by JuhaJGamer** [comment]
I think for timeline visuals it might be reasonable to create coloured "bands" on the screen which shrink or grow as needed, where each band corresponds to a player. Timeline 0 can be a neutral colour, and you can figure out some way of reasonably distributing timelines on either one or both sides of timeline 0. 

As for timeline creation rules, I think one way to dissuade people from spamming new timelines is to just make that a non-viable strategy. Instead of outright banning it, one could (at least in theory) set up a victory conditions such that the more timelines there are the harder it is for any one person to manage the game and the more likely it is that they cause another player to win by accident, meaning that the optimal strategy for every player is to keep the timelines they create to a minimum, and to corner other people into situations which require them to use the timeline element of the game. This would disincentivise creating 10 million timelines, but make it so that the fun time travel mechanic isn't ignored by players, especially causing situations in which time-clutching a game and escaping elimination by a hair can happen. 

I do think individual players might be capable of understanding the game, the input just has to be intuitive. Individuals can pretty easily play 5d chess as well.

**Comment by Pagwin-Fedora** [comment]
> I think for timeline visuals it might be reasonable to create coloured "bands" on the screen which shrink or grow as needed, where each band corresponds to a player. Timeline 0 can be a neutral colour, and you can figure out some way of reasonably distributing timelines on either one or both sides of timeline 0.
> 
> As for timeline creation rules, I think one way to dissuade people from spamming new timelines is to just make that a non-viable strategy. Instead of outright banning it, one could (at least in theory) set up a victory conditions such that the more timelines there are the harder it is for any one person to manage the game and the more likely it is that they cause another player to win by accident, meaning that the optimal strategy for every player is to keep the timelines they create to a minimum, and to corner other people into situations which require them to use the timeline element of the game. This would disincentivise creating 10 million timelines, but make it so that the fun time travel mechanic isn't ignored by players, especially causing situations in which time-clutching a game and escaping elimination by a hair can happen.
> 
> I do think individual players might be capable of understanding the game, the input just has to be intuitive. Individuals can pretty easily play 5d chess as well.

I'd say for timeline creation rules that if the best way to play is just to play normal until you're in a corner, things are kinda just the base game that you could play anywhere else but with a deus ex machina button. Also it would be hard for the time travel to be a deus ex machina like that in any way other than a desperate attempt to delay victory of a player due to the rules of how diplomacy works being based on getting majority control of a board rather than taking a single piece unless you want the victory condition of 5diplomacy to allow for victory through a sum of multiple boards which seems like it would be kinda unintuitive to deal with for players due to victory not being as grounded in the normal rules of diplomacy

**Comment by recursion-ninja** [comment]
> For timeline visuals I think the best solution is to just have timelines appear in the order they were created in top to bottom for games with more than 2 players, other solutions would probably be more complicated and hard to understand.

I agree. However, to play devil's advocate, you could render the multiverse in 3D, with the master/trunk/main timeline continuing linearly forward, and each player  gets a radial segment centered on the main timeline. each radial segment could be rendered as a "pie wedge" extruded into a 3rd dimension with the pointy edge of the 3D pie wedge tangent to the main time line.

**Comment by recursion-ninja** [comment]
I think that the the victory condition should be the following:

A player `W` is the winner if and only if, in the majority (50%+1) of boards int he multiverse, `P` controls at least 50% of the production centers.

My rational for this broad win condition is that if you do not control most of the multiverse, your "winning" board under traditional diplomacy rules is vulnerable to conquest from other timelines. Only by controlling the majority of the multiverse can you be definitively in a secure and dominant position.

In practice, games will likely be ended as a draw with more than one player satisfying the victory conditions under an alliance.

**Comment by Pagwin-Fedora** [comment]
> ### Regarding the Victory Condition:
> 
> I think that the the victory condition should be the following:
> 
> > A player `W` is the winner if and only if, in the majority (50%+1) of boards in the multiverse "present," `W` controls at least 50% of the production centers.
> 
> My rational for this broad win condition is that if you do not control most of the multiverse, your "winning" board under traditional diplomacy rules is vulnerable to conquest from other timelines. Only by controlling the majority of the multiverse can you be definitively in a secure and dominant position.
> 
> In practice, games will likely be ended as a draw with more than one player collaboratively satisfying the victory conditions under an alliance.

I suspect that this would lead to victory coming out of nowhere or just normal diplomacy but the board is bigger and it's harder to understand what unit(s) can do each turn. Also boards where 1 player completely eliminates all other players from the board become very weird as they can't really be contested allowing them to just spawn infinite units and give a permanent boost to victory progress which might be okay, it's hard to say without actual gameplay to observe. If we don't have a hard cap on the number of timelines however this just doesn't work as 1 or more players can just keep making timelines whenever someone gets close to victory

**Comment by Oliveriver** [comment]
I have two main thoughts on the discussion so far.

First, some people aren't appreciating how hard it appears to be to decide where newly-created timelines go. The difficulty comes from Diplomacy having multiple orders being resolved simultaneously. Once the moves and supports are dealt with, you may have several successful time travel jumps in one turn, maybe multiple from each player, and there's no obvious way to enumerate them. You could create some algorithm but I fear it would be pretty arbitrary and unbalanced.

That's in addition to deciding whether timelines go above/below/around and how that's based on the player who created them. My favourite solution to this so far is representing the timeline map in 3D and having the timelines spawn at seven angles around the central timeline, one for each player. But this has a whole bunch of technical issues to work through.

Second, I don't think we can realistically decide whether a given victory condition is the best fit for the game until there's something to test. My gut feel is I'd like it to follow 5D Chess in that winning once by normal Diplomacy rules anywhere on the timeline map is a victory (akin to putting just one king in checkmate anywhere) but I can see reasons why this would be unbalanced. I think we'd need to try a few variations if and when this thing comes to full fruition.

**Comment by isikyus** [comment]
> First, some people aren't appreciating how hard it appears to be to decide where newly-created timelines go.

Are we all clear on _why_ it matters where the timelines go?
I initially didn't see why it matters, but I think I understand now: I have more units on timeline A, and you have more on timeline B, when we create a new timeline C, it matters whether it's next to A (easier for me to attack it), B (easier for you), or both (and we're evenly matched).



In this case I can imagine spawning timelines at 7 angles working. Generally when you spawn a timeline you'd give yourself an advantage there, so you'll naturally end up with a group of "adjacent" timelines where you are stronger, but at a disadvantage when you move into someone else's timeline.
But as you say there are lots of complicated issues — e.g. what happens if England moves into the past of Austria-Hungary's timeline, splitting off a branch — does this go at England's angle? Austria-Hungary's angle? Somewhere else?
A 7-dimensional timeline-space might resolve this but is of course even more confusing.

Maybe it's easier just to say all boards in the same column are adjacent (allow movement), so where you place timelines doesn't matter so much. (So using my original example, timeline C will be next to both timelines A and B regardless of who creates it —  and if another player creates timeline D it'll be adjacent to all three of them).

**Comment by Oliveriver** [comment]
I've been secretly working on a full 5D Diplomacy implementation and have just pushed my progress so far. In the process, I ended up with potential answers to a few of these questions.

A few options for viable victory conditions have appeared:

1. [Jaculabilis' 5D Diplomacy implementation](https://github.com/Jaculabilis/5dplomacy) went with a system where a nation is eliminated from the whole game if it's eliminated from one timeline. Last nation standing wins.
2. My initial idea (and one independently developed by IggyTheFool, [who set up a Discord](https://discord.gg/CxVCUQVhQ5)) is that a player wins if they control >50% of centres in active boards.
3. But I think the best one was created by CaptainMeme of [DiploStrats](https://www.youtube.com/@DiploStrats), who suggests that a player wins if they control 18 unique centres by region name across active boards.

Regarding timeline placement, I realised I had needlessly complicated the situation. The whole thing is massively simplified if timelines are only ever created in one direction, going down. Units from all over the timeline map from any players can arrive on a board, then that whole board splits downards once, if its adjudicated state differs from what it was without the incoming units.

Adjustment is still a bit of a question mark unfortunately.

**Comment by tvanbaak** [comment]
Some thoughts:

One of the things that makes 5D Chess work is that pieces can move in a direction as far as they can go. This makes board states from far in the past relevant to the multiversal frontier, because you never know when a rook might arrive from 10 boards in the future by standing still and moving through time to capture a bishop on the same square in the past.

Diplomacy's only long-distance movement action is the convoy, which requires every participating unit to declare their participation. This is obviously no substitute, since (a) most chess pieces move multiple squares, whereas most orders are not convoys; (b) convoys from the future would require knowing the future positions of units ahead of time, which is much harder than a normal convoy; and (c) it's a highly telegraphed move in a game where surprise is an important tactical resource. (b) and (c) could be mitigated by rules adjustments for future convoys, but (a) is the biggest problem. I don't know if there's a good solution. Some combination of modifications to adjacency rules might playtest well, e.g. counting one timeline over _and_ one turn back as adjacent, making some centers "convoy" units further into the past for free, etc.

As I understand it, your proposal here addresses that issue:

> The whole thing is massively simplified if timelines are only ever created in one direction, going down. Units from all over the timeline map from any players can arrive on a board, then that whole board splits downards once, if its adjudicated state differs from what it was without the incoming units.

If you mean that a timeline "head" is adjacent only to the same season/year in other timelines, then you run into the problem that you can never create multiple timelines from the initial state of a single timeline. You need to be able to move into the past to fork.

If you mean that a timeline "head" is adjacent to _every_ season/year in every timeline, that could work. It might be _too_ loose of an adjacency rule, but we'd have to play it to see.

Another thing that makes 5D Chess work is that each turn is constituted by one player moving one piece. This means that the number of timelines can only increase by one each turn. Diplomacy, on the other hand, has _every_ unit move _every_ turn, which means there could be as many timeline branches as there are units! This creates a lot of issues, not only in-game issues like decision paralysis or strategic fatigue, but also out-of-game issues like how to display all these timelines in the client.

Part of the fun of 5D multiversal time travel is creating alternative timelines, so this can't be solved simply by a hard limit on timelines. My potential solution is to introduce a _sustain phase_ that culls timelines in the way the build/disband phase culls units. One way this could work is that some centers (e.g. the seven capitals) are considered _time centers_. During the sustain phase, each time center "votes" for a timeline, and every timeline with at least one vote stays "live", and the rest "dissolve" -- in game terms, that timeline is no longer playable. Since time centers exist in all timelines, a center's "vote" is split up across the center's owners in all timelines, so e.g. if there are seven timelines, each timeline-center grants 1/7 of a "vote", and 6/7 of a "vote" is insufficient to sustain a timeline.

Another potential solution would be to make it harder to branch timelines. For example, if invading the past carried an inherent -1 attack strength, then you would need at least two units to fork a timeline.

A degenerate case against which adjustment solutions should be checked is the "Fall 1901 zig-zag", where a unit's Fall 1901 move is to move into Spring 1901, causing a timeline fork; the forked timeline then advances to Fall 1901 where the unit repeats the process. If the game only takes orders from the earliest frontier, like in 5D Chess, then the game is essentially stuck in 1901 forever. Either timeline culling needs to occur at a point early enough to prevent this or some other timeline creation rule needs to forbid it.

> But I think the best one was created by CaptainMeme of [DiploStrats](https://www.youtube.com/@DiploStrats), who suggests that a player wins if they control 18 unique centres by region name across active boards.

This is an intriguing idea. It could recreate the "multiversal time traveling checkmate out of nowhere" outcome of 5D Chess when a player just happens to have expanded in one direction in one timeline and in another direction in another timeline.

**Comment by Oliveriver** [comment]
I'm closing this issue as the issue board is being repurposed for tracking boards. Design discussion can now move to the [5D Diplomacy Discord server](https://discord.gg/g7TvjPfkVu). I hope the implementation demonstrates that some of the presumed fundamental problems have been resolved, although it's true that questions around how good the gameplay will actually be remain.
