### ISSUE TITLE
Q: License?

### ISSUE THREAD

**Issue by Jonta** [Oliveriver/5d-diplomacy-with-multiverse-time-travel#2]
AGPLv3+, perhaps? =)

**Comment by JuhaJGamer** [comment]
Why would AGPL be more suitable for this than GPL? They are the same thing, except that 
> If you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there.

This is not a server application. It is not something someone would run on a server. GPLv3+ is enough and more compatible and as such a better license for this work in particular. 

However, were one to modify this into a multiplayer game, they could license the server part to be AGPLv3+ as GPLv3 is, to my knowledge, compatible one-way with AGPLv3. 

I would personally dissuade people from using AGPL if they are copyleft, as of the four fundamental freedoms that underpin the copyleft movement, only three are guaranteed by the license, and one is arguably (though not definitely) explicitly violated (freedom 0). It's not a huge issue to most people but if you do believe in that stuff you should stay clear of AGPL.

**Comment by Oliveriver** [comment]
I made this a quick prototype, so I didn't think about licensing at all. I'm thinking MIT or similar might be best for this codebase then, but I really don't recommend branching from my code if you're trying to do a full implementation.

**Comment by l3gacyb3ta** [comment]
U N L I C E N S E  ~~but that's just me being a radical~~

**Comment by nfitzen** [comment]
[`GPL-3.0-or-later`] is a good license. I think the code is long enough that the extra burden of including the license text is okay.

Regardless of what license you pick, just make sure to [identify licenses clearly][1].

[1]: https://www.gnu.org/licenses/identify-licenses/clearly.html

[`GPL-3.0-or-later`]: https://spdx.org/licenses/GPL-3.0-or-later.html "GNU General Public License v3.0 or later"
[`GPL-3.0-only`]: https://spdx.org/licenses/GPL-3.0-only.html "GNU General Public License v3.0 only"

**Comment by nfitzen** [comment]
> I would personally dissuade people from using AGPL if they are copyleft, as of the four fundamental freedoms that underpin the copyleft movement, only three are guaranteed by the license, and one is arguably (though not definitely) explicitly violated (freedom 0). It's not a huge issue to most people but if you do believe in that stuff you should stay clear of AGPL.

@JuhaJGamer did you mean the [free software movement][1]? The GNU AGPL was literally created by the founder of the movement, Richard Stallman. (That doesn't necessarily imply the license is free as evidenced by the GFDL's invariant sections, but still.) There is no "copyleft movement," and the 4 freedoms you're referring to are [the free software definition][free software]. The GNU AGPL is a free license because it guarantees to all users of the software the 4 freedoms. "Users," in this context, means network users interacting with a server remotely, and the AGPL guarantees to those users as many freedoms as possible. It's specifically designed to combat [SaaSS], which harms users more than proprietary software; if it's wrong for copyleft to prevent that, then it's wrong for copyleft to exist in general.

Because &sect; 13 only covers modified software, and because it only triggers when "users" are interacting over a network, the only thing the AGPL might threaten is freedom 3, since that's what covers your freedom not to publish modified software. However, its condition is at no cost to end users and at a small cost to server hosts. There is no requirement to give any specific user access to the network server, and the only people required to receive source are users interacting with the server. So only people whom the server host wanted to grant access anyway can access the software. Thus, it's a free license, and I've never seen anyone say it's not. (Only the people who complain about copyleft doing its job.)

Of course, the AGPL isn't a practical license in most cases, including this one. So, yeah.

[1]: https://www.gnu.org/philosophy/free-software-intro.html

[free software]: https://www.gnu.org/philosophy/free-sw.html
[SaaSS]: https://www.gnu.org/philosophy/who-does-that-server-really-serve.html "Service as a Software Substitute"

**Comment by throwaway1037** [comment]
@Oliveriver please may you release under a free software license?
Until you do it is illegal for people to use the project in many ways.

The GNU-AGPL-3.0-or-later would be a fine license, especially because networked multiplayer is a feature video games end up adding a lot of the time.

**Comment by JuhaJGamer** [comment]
@nfitzen Sorry for the late reply, yeah, i acknowledge pretty much all of your arguments. However, there's an interesting issue AGPL touches on, that being what part actually is the software and who is the user. If you're browsing the web, are you a user of the web server? Or is the user of the web server the host? If the latter is true (or even if both are), does AGPL technically violate the freedom to use a piece of software without restriction? These aren't unsolvable issues nor are they entirely objective issues, and certainly my opinions change all the time, but that's exactly why I would advise those who don't massively care about it to simply go with standard GPL or even just MIT if they're not particularly concerned. 

Also, while RMS is quite obviously on favour of the license, I'm not Richard Stallman and Richard Stallman isn't the copyleft movement. I prefer to think about these things instead of taking opinions for granted whenever I consider it important enough, though that's fairly rarely.

**Comment by throwaway1037** [comment]
Bump @Oliveriver

**Comment by nfitzen** [comment]
@JuhaJGamer alright, well, another info dump.

<details><summary>Text dump (click to reveal)</summary>

To be honest, my previous argument wasn't very convincing for precisely the reasons you've described. I will note that freedom 0 isn't violated by the AGPL (and, according to the FSF, can't be violated by any copyright license). This is so because the AGPL only triggers its "network condition" when you modify the software. The FSF packages the freedom not to distribute within freedoms 2 and 3 (and in the AGPL's case, only the latter). Anyway, for my argument, this is where we have to break away from the exact wording of the 4 freedoms.

The FSD (in its explanatory sections) specifically states that "You should also have the freedom to make modifications and use them privately in your own work or play, without even mentioning that they exist."

The primary argument one can make is to say that some form of "making available" to the public makes the software no longer private. Although a server operator may be "using" the software, and even if the software itself may not be distributed to the public, if he opens it up to remote network interaction, then he is making the software available to others. It may therefore be useful to require the server operator to distribute it, and crucially, it wouldn't violate his fundamental freedoms.

> Also, while RMS is quite obviously [in] favour of the license, I'm not Richard Stallman and Richard Stallman isn't the copyleft movement. I prefer to think about these things instead of taking opinions for granted whenever I consider it important enough, though that's fairly rarely.

I agree, which is why I mentioned the GNU FDL's invariant sections option. The Debian project, for instance, has concluded that the option makes documentation nonfree.
</details>

**Comment by Oliveriver** [comment]
@throwaway1037 apologies, I completely missed your pings as I had Github notifications turned off.

I've been secretly working on a full 5D Diplomacy implementation recently and I've just pushed what I have so far. I'm going to add a license in the next few days. The game now uses [this map SVG](https://en.wikipedia.org/wiki/Diplomacy_(game)#/media/File:Diplomacy.svg) which is licensed under CC BY-SA 3.0, so that will be a factor in the license for assets.

**Comment by Oliveriver** [comment]
I have now added a GPLv3 license.
